version: '3'
services:
  gatekeeper-frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    entrypoint: ["npm", "start"]
    
  gatekeeper-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - 8080:8080
    entrypoint: ["/bin/api-server"]

