# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Create .env file
      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      working-directory: ./backend
      run: |
            echo $SECRET_KEY > .env
            cat .env
    
    - name: Build
      working-directory: ./backend
      run: go build -o ./cmd/server ./cmd/main.go

    - name: Test
      working-directory: ./backend
      run: go test -v ./tests
